### ISSUE TITLE
Change ORS to UKVS

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/Scholar-Groups#4]
[ORS](https://ws-dl.blogspot.com/2015/09/2015-09-10-cdxj-object-resource-stream.html) was a file format that we considered in the early days of [MementoMap](https://github.com/oduwsdl/MementoMap) work, but we evolved it into [UKVS](https://github.com/oduwsdl/ORS/blob/master/ukvs.md). I would suggest in this work we use UKVS instead. For the most part it is simply a matter of changing the name.

**Comment by phonedude** [comment]
done.
