### ISSUE TITLE
Do we need a custom script for deduplication?

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/Scholar-Groups#7]
I think what `dedup.py` is doing can easily be done using standard Unix `sort` utility.

```sh
$ echo -e 'a 1\na 2\nb 1\na 3\nb 2' | sort -u -t' ' -k1,1
a 1
b 1
```
However, if providing a custom solution is desired then something like the following will be more memory and time efficient (and fewer lines of code too).

```py
#!/usr/bin/env python3

import fileinput

seen = set()
for line in fileinput.input():
    id, _, _ = line.partition(" ")
    if id not in seen:
        seen.add(id)
        print(line, end="")
```

**Comment by phonedude** [comment]
Yeah, I think you're right.

**Comment by phonedude** [comment]
dedup.py has been removed and we're just using sort now.
