### ISSUE TITLE
Consider using GitHub Actions to automate the execution

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/Scholar-Groups#8]
These sets of scripts can be run periodically, on demand, or on certain events automatically using [GitHub Action CI](https://github.com/features/actions) and the results can be committed back to this repo or sent somewhere else. May WS-DL repos are already using it for code linting, testing, compilation, Docker image building, packaging, publishing, and whatnot.

**Comment by phonedude** [comment]
It now uses actions to regenerate the WSDL example data on each PR. There's probably more to be done, but I haven't decided exactly what more we'll want, so I'm closing for now.
